name: soulSnatcher
version: '1.1.0'
main: at.gaderman.soulSnatcher.SoulSnatcher
author: gaderman244
api-version: '1.21'

commands:
  soulIndex:
    description: Opens the index of all souls allowing players to view all info on them
    usage: /soulIndex